apiVersion: v1
kind: Service
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
    - port: 3007        # Service port
      targetPort: 3000  # Container port (Tomcat)
      protocol: TCP
      nodePort: 31000
